import jsPDF from "jspdf";
import type { Entry, LabourPlan, Profile } from "./types";
import {
  formatGestation, formatUKDateLong, formatUKDateTime, gestationFromDueDate,
} from "./gestation";
import { buildPregnancySummaryWeeks, type PregnancySummarySection } from "./pregnancy-summary";
import { t as tFn } from "./i18n";

type PdfOptions = {
  profile: Profile;
  entries: Entry[];
  groupMeasurements: boolean;
  labourPlan?: LabourPlan;
};

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN_X = 18;
const MARGIN_TOP = 18;
const MARGIN_BOTTOM = 18;

export function downloadSummaryPdf(opts: PdfOptions) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  let y = MARGIN_TOP;

  const writable = PAGE_W - MARGIN_X * 2;

  function need(space: number) {
    if (y + space > PAGE_H - MARGIN_BOTTOM) {
      footer(doc);
      doc.addPage();
      y = MARGIN_TOP;
      header(doc, opts.profile, true);
      y += 4;
    }
  }

  function text(s: string, opts2?: { size?: number; bold?: boolean; color?: [number, number, number]; gap?: number }) {
    const size = opts2?.size ?? 10;
    doc.setFontSize(size);
    doc.setFont("helvetica", opts2?.bold ? "bold" : "normal");
    if (opts2?.color) doc.setTextColor(...opts2.color); else doc.setTextColor(20, 20, 30);
    const lines = doc.splitTextToSize(s, writable);
    need(lines.length * (size * 0.42) + (opts2?.gap ?? 1));
    doc.text(lines, MARGIN_X, y);
    y += lines.length * (size * 0.42) + (opts2?.gap ?? 1);
  }

  function rule() {
    need(4);
    doc.setDrawColor(220, 215, 220);
    doc.line(MARGIN_X, y, PAGE_W - MARGIN_X, y);
    y += 3;
  }

  // Title block
  header(doc, opts.profile, false);
  y = MARGIN_TOP + 18;

  // Metadata table
  const g = gestationFromDueDate(opts.profile.dueDateISO);
  const meta: Array<[string, string]> = [
    ["Name", opts.profile.userName],
    ["Baby", opts.profile.babyNickname?.trim() || tFn("baby.fallback")],
    ["Estimated due date", formatUKDateLong(opts.profile.dueDateISO)],
    ["Gestation today", formatGestation(g)],
    ["Generated", formatUKDateTime(new Date())],
  ];
  doc.setFontSize(10);
  meta.forEach(([k, v]) => {
    need(5);
    doc.setFont("helvetica", "normal"); doc.setTextColor(110, 110, 120);
    doc.text(k, MARGIN_X, y);
    doc.setFont("helvetica", "bold"); doc.setTextColor(30, 30, 40);
    doc.text(v, MARGIN_X + 50, y);
    y += 5;
  });
  y += 2;
  rule();

  buildPregnancySummaryWeeks(opts.profile, opts.entries, opts.labourPlan).forEach((week) => {
    text(`Week ${week.week}`, { size: 12, bold: true, color: [180, 80, 100], gap: 2 });
    week.sections.forEach((section) => {
      text(section.title, { size: 10, bold: true, color: [110, 110, 120], gap: 1 });
      sectionPdfLines(section).forEach((line) => text(line, { size: 9, gap: 0.7 }));
      y += 1;
    });
    y += 2;
  });

  // Footer disclaimer
  y += 4;
  rule();
  text(tFn("sum.foot").replace("{name}", opts.profile.userName), { size: 8, color: [120, 120, 130] });

  footer(doc);

  const safeName = (opts.profile.userName || "BumpNotes").replace(/[^a-z0-9\-_]+/gi, "_");
  doc.save(`BumpNotes_Pregnancy_Summary_${safeName}_${new Date().toISOString().slice(0, 10)}.pdf`);
}

function header(doc: jsPDF, profile: Profile, continued: boolean) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(180, 80, 100);
  doc.text("BumpNotes", MARGIN_X, MARGIN_TOP);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110, 110, 120);
  doc.text("Pregnancy Summary", MARGIN_X, MARGIN_TOP + 5);

  doc.setFontSize(9);
  doc.setTextColor(140, 140, 150);
  const right = profile.userName + (continued ? " (cont.)" : "");
  const w = doc.getTextWidth(right);
  doc.text(right, PAGE_W - MARGIN_X - w, MARGIN_TOP);
}

function footer(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 160);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_W - MARGIN_X, PAGE_H - 8, { align: "right" });
    doc.text("Generated by BumpNotes — a personal pregnancy record. Not a medical record.", MARGIN_X, PAGE_H - 8);
  }
}

function sectionPdfLines(section: PregnancySummarySection): string[] {
  if (section.type === "symptoms") {
    return section.items.flatMap((item) => [
      `• ${item.symptom}${item.count > 1 ? ` ×${item.count}` : ""}`,
      ...item.qualifiers.map((qualifier) => `    • ${qualifier}`),
    ]);
  }
  if (section.type === "feelings") {
    return section.items.map((item) => `• ${item.feeling}${item.days > 1 ? `, ${item.days} days this week` : ""}`);
  }
  if (section.type === "people") {
    return section.groups.flatMap((group) => [
      group.professional,
      ...group.items.map((item) => `• ${item}`),
      "",
    ]);
  }
  if (section.type === "measurements") {
    return section.items.flatMap((item) => [item.label, item.value, ""]);
  }
  return section.items.map((item) => `• ${item}`);
}
